server:
  port: 8060
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/get_data_base
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/tamplates/
    suffix: .html
    mode: HTML
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/static/,classpath:/static/,classpath:/public/,file:${web.upload-path}
mybatis:
  type-aliases-package: com.example.download_proccess.entity.Data
  mapper-locations: mapper/*.xml
